FROM python:3.10

RUN apt-get update && apt-get install -y \
    python3-dev libpq-dev wget unzip \
    python3-setuptools gcc bc

RUN pip install 'data-diff==0.7.14' 'data-diff[mysql]==0.7.14' -U

ENTRYPOINT ["data-diff"]